language: python
python:
  - "2.7"
  - "3.5"

script:
  - python setup.py install
  - python examples/banner.py
  - python examples/installer.py
  - python examples/loading.py
  - python examples/progress.py